[SQUASH] laurel_sprout: parts: imported parts
squashed commits from https://github.com/aleeeee1/device_xiaomi_laurel_sprout_old/commits/master/parts

commit 4009107f3d0b678b2de17f42f884e7160cd87d01
Author: Chaohui Wang <chaohuiw@google.com>
Date:   Fri Mar 8 15:24:40 2024 +0530

    laurel_sprout: parts: Migrate to CompoundButton.OnCheckedChangeListener

    Switch and SwitchCompat are both CompoundButton.

    Using CompoundButton in Java will helps migration in the future.

    Bug: 306658427 | AOSP
    Test: manual - check Settings pages
    Test: m RunSettingsLibRoboTests
    Change-Id: I85a70d4c504d8584030ea4a058f30d74206ab835

commit 47f3bc74b5f8b52b2c7b461a2b19ae11f763a3c2
Author: aleeeee1 <pace.alessandro05@protonmail.com>
Date:   Mon Mar 25 13:19:01 2024 +0000

    parts: change import from widget to collapsingtoolbar

commit f3c3797d5b395c80652f78601bd68d1942194388
Author: Nipin NA <nipinna0@gmail.com>
Date:   Sat Jul 23 08:53:57 2022 +0530

    laurel_sprout: parts: Fix Raise to wake icon on dark mode

commit 5cac658135c239ab05663d2c8c0576febea2c0ba
Author: palaych <palaychm@yandex.ru>
Date:   Sat Dec 11 03:43:08 2021 +0900

    laurel_sprout: parts: Import IntentFilter

    Change-Id: Iab3aa4fdb559864c22dd5a7b2c6df7385c0f0cb8

commit b864cc922c725b9061d0a1d0b715aab8285b3607
Author: Nauval Rizky <enuma.alrizky@gmail.com>
Date:   Fri Jan 31 11:57:48 2020 +0900

    laurel_sprout: parts: Introduce raise to wake gesture

    * Highly inspired by iOS raise to wake
    * Add min interval for raise2wake
    * Check proximity before wakeup

    Signed-off-by: Nauval Rizky <enuma.alrizky@gmail.com>
    Signed-off-by: David Setiawan <fryevia@foxmail.com>

commit 206190522770d096a999b384161e3332a66fbb3d
Author: Mudabbirul Saad <mudabbirulsaad@gmail.com>
Date:   Mon Feb 13 00:11:24 2023 +0600

    laurel_sprout: Fix compilation error for r16 tag.

    error: cannot find symbol
    import com.android.settingslib.collapsingtoolbar.R;

commit 6c1734e53b78732c1a1da8e9ba8725d9c3949b3e
Author: yashlearnpython <73551736+yash3056@users.noreply.github.com>
Date:   Sun Jul 25 20:22:24 2021 +0530

    laurel_sprout: Add permission for Xiaomiparts

    this is being added to stop xiaomiparts being killed

    07-28 20:06:35.938  1454  1454 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
    07-28 20:06:35.938  1454  1454 E AndroidRuntime: java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {org.lineageos.settings (/system_ext/priv-app/XiaomiParts): android.permission.WRITE_SECURE_SETTINGS, org.lineageos.settings (/system_ext/priv-app/XiaomiParts): android.permission.INTERACT_ACROSS_USERS}

    Signed-off-by: Anush02198 <Anush.4376@gmail.com>
    Signed-off-by: Joey Huab <joey@evolution-x.org>

commit ad2cd24d8a647e52c40a41276549d31f498b7e0a
Author: AshutoshSundresh <ashutoshsundresh@gmail.com>
Date:   Tue Aug 11 19:39:00 2020 +0200

    laurel_sprout: parts: Add icon for Clear Speaker

    * Source: https://github.com/Ashutosh-s-Test-Dumpster/device_oneplus_sdm845-common/commit/d9d25ff406153a34b9cb9b59ba8de026f20ee6da

    Signed-off-by: Adithya R <gh0strider.2k18.reborn@gmail.com>
    Signed-off-by: Joey Huab <joey@evolution-x.org>

commit c4e6d8fcdec1d26a56899d753c00ca5caab0631a
Author: Volodymyr Zhdanov <wight554@gmail.com>
Date:   Tue Oct 19 03:18:42 2021 +0300

    laurel_sprout: parts: Drop useless SettingsLib dependency

    Former-commit-id: fef608cc3d4984cc21efd88a175337ff6a3a5055
    Signed-off-by: Joey Huab <joey@evolution-x.org>

commit d10f598f70d8acda472afbc5ea0606afe557e994
Author: Volodymyr Zhdanov <wight554@gmail.com>
Date:   Wed Oct 20 18:04:39 2021 +0300

    laurel_sprout: parts: Fix Clear Speaker IllegalStateException

    * trace:
      E AndroidRuntime: java.lang.IllegalStateException
      E AndroidRuntime: 	at android.media.MediaPlayer._stop(Native Method)
      E AndroidRuntime: 	at android.media.MediaPlayer.stop(MediaPlayer.java:1397)

    * also do small refactoring while at it

    Former-commit-id: 98f1335384a6b534becf87ad54333f737de9e15e
    Signed-off-by: Joey Huab <joey@evolution-x.org>

commit 71f85054e03cef5e683b6f0a8068715ad3ef1f56
Author: Joey Huab <joey@evolution-x.org>
Date:   Thu Dec 9 13:38:08 2021 +0900

    laurel_sprout: parts: Adapt Clear Speaker to S style

    Signed-off-by: Joey Huab <joey@evolution-x.org>

commit 288b61ba891bf874c1165dc2a086c0e4958da4cb
Author: Adithya R <gh0strider.2k18.reborn@gmail.com>
Date:   Sat Jun 12 15:03:03 2021 +0530

    laurel_sprout: parts: Add headphones warning for clear speaker

    Change-Id: I70ad24bceac2f6538e1fbfd79d70bd5ca64eee07
    Signed-off-by: Joey Huab <joey@evolution-x.org>

commit f9b5215539eb58821e7d8869cee07d24d24460ef
Author: Adithya R <gh0strider.2k18.reborn@gmail.com>
Date:   Sat Jun 12 15:02:54 2021 +0530

    laurel_sprout: parts: Update clear speaker audio from MIUI 12

    Change-Id: I7aada005798a6ef1e07f3b2424fd02ba58293018
    Signed-off-by: Joey Huab <joey@evolution-x.org>

commit 4a85409b1b0ee963a78fa95e291a586ceca9b10a
Author: Jyotiraditya <jyotiraditya@aospa.co>
Date:   Wed Jun 24 13:07:55 2020 +0200

    laurel_sprout: parts: Implement Clear Speaker

    Co-authored-by: Adithya R <radithya2002@gmail.com>
    Signed-off-by: Jyotiraditya <jyotiraditya@aospa.co>
    Change-Id: I23b8ebd106502e083b6feec9b58efd76e49d3367
    Signed-off-by: Joey Huab <joey@evolution-x.org>

commit 0ab43e132ccc23272237204dfd9acc37b3c51d93
Author: maxwen <max.weninger@gmail.com>
Date:   Wed Dec 23 20:02:03 2020 +0530

    laurel_sprout: parts: Add HBM qs tile

    Signed-off-by: Pranav Temkar <pranavtemkar@gmail.com>
    Signed-off-by: Joey Huab <joey@evolution-x.org>

commit 7240a255553ef94bd6550baefb061bc4e70100fa
Author: Adhitya Mohan <me@adhityamohan.in>
Date:   Thu Dec 3 06:03:08 2020 +0530

    laurel_sprout: parts: Set priority for Display Settings switch

     * Display settings has diffrent fragments, so set order to make it appear properly

    Signed-off-by: Pranav Temkar <pranavtemkar@gmail.com>
    Signed-off-by: Joey Huab <joey@evolution-x.org>

commit 3d4016246bbea6365ac0f10afce22cd94e2234dd
Author: Adhitya Mohan <me@adhityamohan.in>
Date:   Wed Dec 2 18:30:11 2020 +0530

    laurel_sprout: parts: Implement HBM switch

    Signed-off-by: Pranav Temkar <pranavtemkar@gmail.com>
    Signed-off-by: Joey Huab <joey@evolution-x.org>

commit 842c1471e93f75217843cb6c00dec6de4d846fd2
Author: Henrique Silva <jhenrique09.mcz@hotmail.com>
Date:   Tue Jan 18 22:31:59 2022 -0300

    laurel_sprout: parts: Fix missing ambient display string

commit d0aec9240f4e929e7eb11dcb816e8f60ac72a3ce
Author: Ratoriku <a1063021545@gmail.com>
Date:   Mon May 24 22:06:08 2021 +0800

    laurel_sprout: parts: Add missing symbol

    Signed-off-by: Ratoriku <a1063021545@gmail.com>

commit 85fbd9a0595b17e7be2abe297f546d58558913b3
Author: TheScarastic <warabhishek@gmail.com>
Date:   Wed Oct 6 07:25:13 2021 +0000

    laurel_sprout: parts: Adapt to S style

     * Use Theme.SubSettingsBase for theme
     * Replace PreferenceActivity with CollapsingToolbarBaseActivity
     * Add Titles to preference screen
     * Remove onOptionsItemSelected and where neccessary move to activity

    Change-Id: I25f6dce7cf202487898facfa66e57ced86a85594

commit ea19851cf920bc99299f95576db4e8f4e8a034b7
Author: TheScarastic <warabhishek@gmail.com>
Date:   Wed Oct 6 07:25:04 2021 +0000

    laurel_sprout: parts: Inject doze preference through ia

    Change-Id: Id62c6ee2e696acb1906413747da912cc950e27d0

commit 1a2ce2f6e3b798ee5b1f90504d8a0164a4f55ca5
Author: kubersharma001 <kubersharma001@gmail.com>
Date:   Wed Sep 1 15:22:57 2021 +0000

    laurel_sprout: parts: Bump target SDK version to 30

    Change-Id: I58c2aca6d6e4466ddb6d09cabc8310c479a02027

commit a7282178ab0604b1e49c73d5db25171f8be5393d
Author: ShubhamB <shubhamprince111@gmail.com>
Date:   Sun Mar 21 23:41:44 2021 +0530

    laurel_sprout: parts: Make HelpDialogFragment class public

    * Unable to start activity ComponentInfo{org.lineageos.settings/org.lineageos.settings.doze.DozeSettingsActivity}: java.lang.IllegalStateException: Fragment org.lineageos.settings.doze.DozeSettingsFragment.HelpDialogFragment must be a public static class to be  properly recreated from instance state.

    Signed-off-by: ShubhamB <shubhamprince111@gmail.com>
    Change-Id: Id48c903f4b6745baf26bc88b95c8425554b36f06

commit c0da54f45bebdd9b01980c1f20e607c1b95df8b8
Author: Bruno Martins <bgcngm@gmail.com>
Date:   Wed Jan 6 20:51:54 2021 +0000

    laurel_sprout: parts: Use all shared resources from devicesettings

    Change-Id: Icd7f381c574ea36eb4d797cefd60ba9f1a0941bd

commit 4a586d6f6ba5b4f2fd8cdb9294860bfa54484a9f
Author: Pig <pig.priv@gmail.com>
Date:   Fri Dec 18 00:40:41 2020 +0800

    laurel_sprout: parts: Convert to Android.bp

    Change-Id: Iecd8bbc5f1351ad29c974ef08dd3948eabacf2b3

commit 9ff1e36e805b1bd3b3f4042800dae47288c74477
Author: Pig <pig.priv@gmail.com>
Date:   Wed Dec 16 10:28:31 2020 +0800

    laurel_sprout: parts: Move them to /system_ext

    Change-Id: I564276782de81b78866a7d5c3cb3de3230231c85

commit 51990dd0dd9d4e45d2e6e62635dbc3f71811822f
Author: Luca Stefani <luca.stefani.ge1@gmail.com>
Date:   Sun Sep 2 12:46:45 2018 +0200

    laurel_sprout: parts: Add local FileUtils

    * We don't really need lineageos sdk for one class

    Change-Id: I5e06015c8ea65399bb3643183dd17641ca0d3ad7

commit 53bd4ee9f9fd259b7bcd38f5cdb25f16d0d2a954
Author: arian <arian.kulmer@web.de>
Date:   Sat Dec 15 15:55:55 2018 +0100

    laurel_sprout: parts: Add icons for doze

    Change-Id: Ibbb18065f97ed6f8f5376752495255aeafe1db82

commit 966fac598808b44bae1ee9b0abb4006f6e64aa52
Author: TH779 <tongsj2333@gmail.com>
Date:   Sat Sep 5 22:24:11 2020 +0800

    laurel_sprout: Import XiaomiParts from sdm845-common

     * From https://github.com/LineageOS/android_device_xiaomi_sdm845-common/commit/65f0dd1a73e2088ceeca6922adef90fde21420e9.

    Signed-off-by: TH779 <tongsj2333@gmail.com>
    Change-Id: Idf661a96f770a70725c38e13edcc28ab379af2b6

laurel_sprout: sepolicy: Address XiaomiParts sepolicy rules

Signed-off-by: Arturo <rtsanonynousperson@gmail.com>